# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3URL', models.CharField(max_length=2000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
